[package]
name = "dfmt"
authors = ["Tom Dymel <tom@dymel.dev>"]
version = "0.1.0"
edition = "2024"
keywords = [
    "dynamic",
    "dyn",
    "format",
    "fmt",
    "string",
    "str",
    "args",
    "arguments",
]
categories = ["no-std"]
description = "A fully featured dynamic drop in replacement for the format! macro."
readme = "README.md"
repository = "https://github.com/tdymel/dyn-str-fmt"
documentation = "https://docs.rs/dyn-str-fmt"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "2"

[dev-dependencies]
criterion = "0"

[[bench]]
name = "performance"
harness = false

[features]
nightly_formatting_options = []
